// Composers for the search page's "Popular composers" chips, as HVSC credits them.
// Chosen from CSDb's musician top list (weighted average 8.5 or higher,
// 2026-09-24) plus the classic names; nothing beyond the HVSC credit is kept.
export const COMPOSERS = [
  "Rob Hubbard",
  "Markus Klein (LMan)",
  "Jeroen Tel",
  "Michael P. Bridgewater (Mibri)",
  "Marcin Majdzik (psych858o)",
  "Kamil Wolnikowski (Jammer)",
  "Sascha Zeidler (Linus)",
  "Jason Page",
  "Johan Samuelson (Stinsen)",
  "Thomas Mogensen (DRAX)",
  "Sami Juntunen (Mutetus)",
  "Tobias Göhlke (Toggle)",
  "Reyn Ouwehand",
  "Toni Lönnberg (!Cube)",
  "Søren Lund (Jeff)",
  "Johannes Bjerregaard",
  "Tim Follin",
  "Peter Siekmann (Devilock)",
  "Aidan Crouzet-Pascal (acrouzet)",
  "Hein Holt",
  "Martin Galway",
  "Owen Crowley (Conrad)",
  "Ben Daglish",
  "Thomas E. Petersen (Laxity)",
  "Ole Marius Pettersen",
  "Wojciech Radziejewski (Shogoon)",
  "Thomas Detert",
  "Stein Pedersen",
  "Alexander Wiklund (Wiklund)",
  "Volker Meitz (PRI)",
  "Charles Deenen",
  "Ari-Pekka Paljakka (Zardax)",
  "Stellan Andersson (Dane)",
  "Matt Simmonds (4-Mat)",
  "Oliver Kläwer",
  "Thomas Bendt (Scortia)",
  "Jonathan Dunn",
  "Kjell Nordbø",
  "Sanke Michael Choe (SMC)",
  "Antony Crowther",
  "Figge Wasberger (Fegolhuzz)",
  "Adam Waclawski (Wacek)",
  "fieserWolF",
  "Matt Gray",
  "Steven Diemer (A-Man)",
  "Neil Baldwin (Demon)",
  "Antti Hannula (Flex)",
  "Geir Tjelta",
  "Sami Seppä (Rock)",
  "Edwin van Santen",
  "Alexander Rotzsch (Fanta)",
  "Graham Marsh (BOGG)",
  "Kai Walter (PVCF)",
  "Torben Hansen (Metal)",
  "Kristian Røstøen",
  "Tufan Uysal (SoNiC)",
  "Jens-Christian Huus",
  "Klaus Grøngaard (Link)",
  "Tomas Danko",
  "Carsten Berggreen (Scarzix)",
  "Tammo Hinrichs (KB)",
  "Jaakko Kaitaniemi (Reed)",
  "Ari Yliaho (Agemixer)",
  "Michal Hoffmann (Randall)",
  "Sascha Nagie (celticdesign)",
  "Morten Kristensen (MSK)",
  "Anders Carlsson (Goto80)",
  "Aleksi Eeben",
  "Stefan Uram (Orcan)",
  "Alexander Ney (Taxim)",
  "Dejan Subotin (DaFunk)",
  "Matthias Hartung (The Syndrom)",
  "Lars Hoff",
  "Piotr Kuciapski (Wizard)",
  "Jouni Ikonen (Mixer)",
  "Eddie Svärd (Ed)",
  "Joachim Wijnhoven (Yogibear)",
  "Marcin Kubica (Booker)",
  "Mario Laugell (Steel)",
  "David Whittaker",
  "Guy Shavitt",
  "Timo Taipalus (Abaddon)",
  "Markus Schneider (Diflex)",
  "Wojciech Wardynski (Praiser)",
  "Alain Hertenstein (Iron Cat)",
  "Andreas Samuelsson (Mr. Death)",
  "Janne Suni (Tempest)",
  "Arman Behdad (Intensity)",
  "Linus Nielsen (Boogaloo)",
  "Zoltán F. Földi (Eclipse)",
  "Ronny Engmann (dalezy)",
  "M. Nilsson-Vonderburgh (Mitch)",
  "Attila Szõke (da Blondie)",
  "Anders Rodahl (Rage)",
  "Chris Hülsbeck",
];

// HVSC credits that should show (and search) as another name: handles that
// are ambiguous on their own, or one composer credited several ways.
export const COMPOSER_ALIASES = {
  "Glenn Rune Gallefoss (Shark)": "Glenn Rune Gallefoss",
  "Shark": "Glenn Rune Gallefoss",
};
