#!/usr/bin/env python3
"""Write firestore.rules from the template firestore.rules.in, with the
accepted tag ids from js/tags-vocab.json filled in.

firestore.rules isn't in git: run this before anything that reads it (the
emulator checks; tools/deploy_rules.py and the unit tests run it themselves).
The vocabulary stays the one place the tag ids are kept.

The rules accept every id in the vocabulary's groups plus those under
"retired": tags taken out of the app. A retired id is hidden in the app but
still accepted, so a device still running the previous version can save a
tune that has it. Never delete an id from the JSON: move it to "retired".
tools/deploy_rules.py refuses to deploy rules that drop an accepted id.

Usage:
  tools/build_rules.py
"""

import argparse
import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TEMPLATE = REPO / "firestore.rules.in"
RULES = REPO / "firestore.rules"
VOCAB = REPO / "js" / "tags-vocab.json"
TAG_ID = re.compile(r"^[a-z0-9-]{1,24}$")
PLACEHOLDER = "{{TAG_IDS}}"
TAG_IDS = re.compile(r"function tagIds\(\)\s*\{\s*return\s*\[(.*?)\]", re.S)


def accepted_ids(vocab):
    """Active ids then retired ones, validated: well formed, unique, not both."""
    active = [t["id"] for g in vocab["groups"] for t in g["tags"]]
    retired = vocab.get("retired", [])
    problems = [f"bad id {i!r}" for i in active + retired if not isinstance(i, str) or not TAG_ID.match(i)]
    for name, ids in (("groups", active), ("retired", retired)):
        problems += [f"{i!r} repeated in {name}" for i in sorted(set(ids)) if ids.count(i) > 1]
    problems += [f"{i!r} is both a tag and retired" for i in sorted(set(active) & set(retired))]
    if problems:
        raise SystemExit("js/tags-vocab.json: " + "; ".join(problems))
    return active + retired


def ids_in_rules(text):
    """The ids a rules file's tagIds() accepts, or None if it has none."""
    match = TAG_IDS.search(text)
    return re.findall(r"'([a-z0-9-]+)'", match.group(1)) if match else None


GENERATED = "// Generated by tools/build_rules.py from firestore.rules.in and js/tags-vocab.json. Don't edit: edit those."


def render(template, ids):
    """The template with {{TAG_IDS}} replaced by the list of ids, and its own
    // TEMPLATE: note swapped for one saying the result is generated."""
    if template.count(PLACEHOLDER) != 1:
        raise SystemExit(f"firestore.rules.in needs {PLACEHOLDER} exactly once")
    listed = "[\n" + ",\n".join(f"        '{i}'" for i in ids) + "\n      ]"
    text = template.replace(PLACEHOLDER, listed)
    lines = [line for line in text.split("\n") if not line.startswith("// TEMPLATE:")]
    return "\n".join(lines).replace("\n\n", f"\n\n{GENERATED}\n", 1)


def build():
    """Write a fresh firestore.rules; returns its content."""
    ids = accepted_ids(json.loads(VOCAB.read_text()))
    content = render(TEMPLATE.read_text(), ids)
    RULES.write_text(content)
    print(f"firestore.rules: {len(ids)} tag ids")
    return content


def main():
    argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter).parse_args()
    build()


if __name__ == "__main__":
    main()
